### ISSUE TITLE
@cache decorator

### ISSUE THREAD

**Issue by DanielSWolf** [jayphelps/core-decorators#104]
When writing classes, I sometimes want lazy properties: Read-only properties whose value is calculated on first access, then cached for later access.

MDN [describes a pattern to implement this](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/get#Smart_self-overwriting_lazy_getters), but code following this pattern looks rather strange. It would be much simpler if there was a `@cache` decorator for `get` properties.

Does this functionality already exist? If not, I might implement it myself. In that case, would you be interested in a pull request?

**Comment by jayphelps** [comment]
Sounds like you want the [`@lazyInitialize` decorator](https://github.com/jayphelps/core-decorators.js#lazyinitialize) no?

**Comment by DanielSWolf** [comment]
The intended outcome is the same, but the input is different. Consider the following code:

```js
class Editor {
  @lazyInitialize
  hugeBuffer1 = createHugeBuffer();

  @cache
  get hugeBuffer2() {
    const result = [];
    for (let i = 0; i < 1000; i++) {
      result.push(i);
    }
    return result;
  }
}
```

*Without* the decorators, `hugeBuffer1` would be initialized eagerly, then remain constant, while `hugeBuffer2` would be evaluated on every access. *With* the decorators, they should behave identically.

**Comment by jayphelps** [comment]
So you're wanting one that caches getters, not initializers?

**Comment by DanielSWolf** [comment]
Exactly.

**Comment by jayphelps** [comment]
Is there a use case that is better as a getter instead of an initializer? Having trouble with this one. Feels like initializers have a clearer intent in this case.

**Comment by DanielSWolf** [comment]
There are two situations where I'd prefer the getter style.

First, whenever the property's value depends on `this`. Property initializers normally run before the constructor, so the following code doesn't work (*without* a decorator):

```js
class Foo {
  constructor(foo) {
    this.foo = foo;
  }

  bar = someFunction(this.foo);
}
```

Adding `@lazyInitialize` to `bar` will probably make it work. But it feels wrong to me to rely on this behavior. Any decent linter will probably tell me that I cannot access `this` in a property initializer.

Second, whenever calculating the property's value requires more than a single expression. Sure, I could write a method `computeInitialFoo()`, then say `foo = this.computeInitialFoo()`. But introducing a new method just to initialize a property adds visual noise. I find it much cleaner to write the initialization logic *within the property itself*, then add a decorator so that the result is cached.

**Comment by jayphelps** [comment]
> Property initializers normally run before the constructor

At the risk of being pedantic, this isn't strictly true. As they are [currently spec'd](https://tc39.github.io/proposal-class-public-fields/#[[construct]]), they do have access to `this` and are initialized during the `[[Construct]]` phase. So you _can_ do this:

```js
class Foo {
  message = 'hello world';
  first = this.message;

  constructor() {
    this.second = this.first;
  }
}

let foo = new Foo();

console.log(foo.first === 'hello world');
console.log(foo.second === 'hello world');
```

But you're correct that you can't access constructor arguments or fields you initialize explicitly inside the constructor body itself, because they happen _after_ public class field initializers are run.

***

I see your other arguments. I stil think the intent is clearer to not use a getter, but that's just my personal preferences.

Can you think of a more applicable name than `@cache`?

**Comment by DanielSWolf** [comment]
I discussed the naming with a colleague. We agree that `@cache` is too generic. But `@memoize` might be just right in that it precisely expresses the intent.

Regarding the applicability: In the long run, it might in fact be a good idea for the `@memoize` decorator to support both property getters and plain functions.

**Comment by jayphelps** [comment]
We currently have an [undocumented memoize decorator](https://github.com/jayphelps/core-decorators.js/commit/9201eaba7ee0664972e551e63888aa35dcccef77) that is deprecated because I found it was hard to maintain alignment with lodash's implementation. Instead, I now recommend people use lodash:

```js
import { memoize } from 'lodash';

class Foo {
  @decorate(memoize)
  computeSomething(arg) {
    // stuff
  }
}
```

The trouble with that is that it doesn't work with getters, as described in #65. Which...is intentionally because (as elaborated in #65) I'm not aware of a way to actually make it work correctly in all cases--the "bugs" it would be pretty confusing for users.

**Comment by DanielSWolf** [comment]
Oh dear -- I didn't realize I was stirring up a hornet's nest!

I skimmed the issues you linked, and I appreciate the difficulty. I do think the matter is worth pursuing, though. I'll try to find some time to fully grok the matter.

**Comment by matthewrobb** [comment]
Just throwing this out there: `@lazyValue get foo() {}` since we're talking about a run-once computed value prop.

**Comment by DanielSWolf** [comment]
It turns out that the decorator I need is very easy to write from scratch. I would have liked to get it up to this project's standards, but I'm afraid I don't have the time right now. So I'm closing this issue.

In case anybody else finds themselves in my situation, here's the code (fully tested, but tests omitted).

```js
// Memoization decorator for properties (instance or static).
// See https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/get
export function memoize(target, key, descriptor) {
  const isPropertyGetter = descriptor && descriptor.get && !descriptor.set;
  if (!isPropertyGetter) {
    throw new Error('@memoize can only be used on property getters.');
  }

  const originalGetter = descriptor.get;
  descriptor.get = function memoizingGetter() { // eslint-disable-line no-param-reassign
    const result = originalGetter.call(this);
    Object.defineProperty(this, key, { value: result });
    return result;
  };
  return descriptor;
}
```
